version: '3'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    #depends_on:
    #  - mongo
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    networks:
      churchapi:
        ipv4_address: 172.1.0.2

networks:
  churchapi:
    ipam:
      config:
        - subnet: 172.1.0.0/16